### ISSUE TITLE
HI，@daigo0927

### ISSUE THREAD

**Issue by 1995hzczjut** [daigo0927/WGAN_GP#1]
Do you solve the problem about loss later？

**Comment by daigo0927** [comment]
I'm really sorry about the delayed reply ...
I guess that i've watched ```self.g_loss``` and ```self.d_loss #(gradient penalty added)``` as loss for generator and discriminator.
**But the value we should concern is Wasserstein distance, and this is ```self.d - self.d_``` in line98**
I have modified that part, and the getting-larger-loss problem might be solved.
